version: 2
jobs:
  build:
    docker:
      - image: gcc:7
    steps:
      - checkout
      - run:
          name: Install CMake
          command: |
            apt-get update && apt-get install -y --no-install-recommends cmake
      - run:
          name: Install NodeJS
          command: |
            git clone https://github.com/creationix/nvm.git ~/.nvm
            cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`
            source ~/.nvm/nvm.sh
            nvm install v6
      - run:
          name: Check versions
          command: |
            uname -a
            g++ --version
            cmake --version
            make --version
            npm version

      - run:
          name: Build and test in C++98 mode
          command: |
            ./scripts/build_from_scratch.sh '-DUSE_CPP11=OFF'
            ./scripts/run_tests.sh
      - run:
          name: Build and test in C++11 mode
          command: |
            ./scripts/build_from_scratch.sh '-DUSE_CPP11=ON'
            ./scripts/run_tests.sh
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
