version: 2
jobs:
  build:
    docker:
      - image: gcc:7
    steps:
      - checkout
      - run:
          name: Install cmake and check versions
          command: |
            apt-get update && apt-get install -y --no-install-recommends cmake
            uname -a
            g++ --version
            cmake --version
            make --version
      - run:
          name: Build and test in C++98 mode
          command: |
            ./scripts/build_from_scratch.sh '-DUSE_CPP11=OFF'
            ./scripts/run_tests.sh
      - run:
          name: Build and test in C++11 mode
          command: |
            ./scripts/build_from_scratch.sh '-DUSE_CPP11=ON'
            ./scripts/run_tests.sh

